<?php include('inc/header.php');?>

<!-- Begin Page Content -->
<div class="container-fluid">

    <h1 class="h3 mb-4 text-gray-800">Beranda</h1>      

    <!-- Content Row -->
    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-6 mb-4">

            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">OOTD #1</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <!-- <div class="dropdown-header">Dropdown Header:</div> -->
                            <a class="dropdown-item" href="#">Tambahkan ke Pin</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4 rounded" style="width: 20rem;"
                            src="img/ega.jpg" alt="...">
                    </div>
                    <p>Baju yang cocok disaat cuaca panas, karena warnanya yang cerah dapat memanulkan cahaya sehingga tidak cepat menyerap panas.</p>
                    <a target="_blank" rel="nofollow" href="#">Link ecommerce</a>
                </div>
            </div>

            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">OOTD #2</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <!-- <div class="dropdown-header">Dropdown Header:</div> -->
                            <a class="dropdown-item" href="#">Tambahkan ke Pin</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4 rounded" style="width: 20rem;"
                            src="img/ega.jpg" alt="...">
                    </div>
                    <p>Baju yang cocok disaat cuaca panas, karena warnanya yang cerah dapat memanulkan cahaya sehingga tidak cepat menyerap panas.</p>
                    <a target="_blank" rel="nofollow" href="#">Link ecommerce</a>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- /.container-fluid -->

<?php include('inc/footer.php');?>